name: Android Builds

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: jdx/mise-action@v3

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key:
            gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties',
            '**/gradle.properties') }}
          restore-keys: |
            gradle-

      - name: Set Up JDK
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install
        run: |
          npm i -g corepack@latest
          corepack enable
          yarn
          bundle install

      - name: Build Project
        run: |
          bundle exec fastlane android build

      - name: Upload APK Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: feedit-apk
          path: ./dist/android/*.apk
